"""Generate a parking receipt image using Pillow."""
from datetime import datetime
from PIL import Image, ImageDraw, ImageFont
import os


class SlipCreator:
    def __init__(self, bold_font_path: str, regular_font_path: str, fee: str = "Rs. 30.00"):
        self.bold_font = bold_font_path
        self.regular_font = regular_font_path
        self.fee = fee

    def _load_fonts(self):
        try:
            return (
                ImageFont.truetype(self.bold_font, 32),
                ImageFont.truetype(self.regular_font, 18),
                ImageFont.truetype(self.bold_font, 20),
                ImageFont.truetype(self.regular_font, 13),
                ImageFont.truetype(self.regular_font, 20),
            )
        except Exception:
            fallback = ImageFont.load_default()
            return (fallback,) * 5

    def make_receipt(self, plate_text: str, timestamp: datetime, out_path: str):
        width, height = 600, 400
        colors = {
            "background": "#F8F9FA",
            "header": "#2C3E50",
            "sub": "#7F8C8D",
            "accent": "#BDC3C7",
        }
        canvas = Image.new("RGB", (width, height), colors["background"])
        draw = ImageDraw.Draw(canvas)
        title_f, text_f, value_f, small_f, icon_f = self._load_fonts()

        # outer frame
        draw.rounded_rectangle((20, 20, width - 20, height - 20), radius=10, outline=colors["accent"], width=2)

        # header text
        header = "VEHICLE PARKING RECEIPT"
        hb = draw.textbbox((0, 0), header, font=title_f)
        draw.text(((width - (hb[2] - hb[0])) / 2, 40), header, font=title_f, fill=colors["header"])

        y = 120
        items = [
            ("🚗", "Plate No", plate_text),
            ("🕒", "Entry", timestamp.strftime("%d %b %Y %H:%M:%S")),
            ("💰", "Fee", self.fee),
        ]
        for icon, label, val in items:
            draw.text((40, y), icon, font=icon_f, fill=colors["header"])
            draw.text((80, y), label, font=text_f, fill=colors["sub"])
            draw.text((350, y), val, font=value_f, fill=colors["header"])
            y += 50

        footer = "Generated by ParkingEngine"
        fb = draw.textbbox((0, 0), footer, font=small_f)
        draw.text(((width - (fb[2] - fb[0])) / 2, height - 30), footer, font=small_f, fill=colors["sub"])

        canvas.save(out_path)
        return out_path
